// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using japanese_character_practices.Components.Data;

#nullable disable

namespace japanese_character_practices.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20260211193845_InicialCreate")]
    partial class InicialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SuteganaHiraganaYouonHiragana", b =>
                {
                    b.Property<string>("SuteganaHiraganasUnicode")
                        .HasColumnType("TEXT");

                    b.Property<int>("YouonHiraganaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SuteganaHiraganasUnicode", "YouonHiraganaId");

                    b.HasIndex("YouonHiraganaId");

                    b.ToTable("SuteganaHiraganaYouonHiragana");
                });

            modelBuilder.Entity("SuteganaKatakanaYouonKatakana", b =>
                {
                    b.Property<string>("SuteganaKatakanasUnicode")
                        .HasColumnType("TEXT");

                    b.Property<int>("YouonKatakanaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SuteganaKatakanasUnicode", "YouonKatakanaId");

                    b.HasIndex("YouonKatakanaId");

                    b.ToTable("SuteganaKatakanaYouonKatakana");
                });

            modelBuilder.Entity("japanese_character_practices.Components.Model.GojuuonHiragana", b =>
                {
                    b.Property<string>("Unicode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDakuten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Japanese")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Unicode");

                    b.ToTable("GojuuonHiragana");
                });

            modelBuilder.Entity("japanese_character_practices.Components.Model.GojuuonKatakana", b =>
                {
                    b.Property<string>("Unicode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDakuten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Japanese")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Unicode");

                    b.ToTable("GojuuonKatakana");
                });

            modelBuilder.Entity("japanese_character_practices.Components.Model.SuteganaHiragana", b =>
                {
                    b.Property<string>("Unicode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDakuten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Japanese")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Unicode");

                    b.ToTable("SuteganaHiragana");
                });

            modelBuilder.Entity("japanese_character_practices.Components.Model.SuteganaKatakana", b =>
                {
                    b.Property<string>("Unicode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDakuten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Japanese")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Unicode");

                    b.ToTable("SuteganaKatakana");
                });

            modelBuilder.Entity("japanese_character_practices.Components.Model.YouonHiragana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Roman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnicodeBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnicodeBase");

                    b.ToTable("YouonHiragana");
                });

            modelBuilder.Entity("japanese_character_practices.Components.Model.YouonKatakana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Roman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnicodeBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnicodeBase");

                    b.ToTable("YouonKatakana");
                });

            modelBuilder.Entity("SuteganaHiraganaYouonHiragana", b =>
                {
                    b.HasOne("japanese_character_practices.Components.Model.SuteganaHiragana", null)
                        .WithMany()
                        .HasForeignKey("SuteganaHiraganasUnicode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("japanese_character_practices.Components.Model.YouonHiragana", null)
                        .WithMany()
                        .HasForeignKey("YouonHiraganaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SuteganaKatakanaYouonKatakana", b =>
                {
                    b.HasOne("japanese_character_practices.Components.Model.SuteganaKatakana", null)
                        .WithMany()
                        .HasForeignKey("SuteganaKatakanasUnicode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("japanese_character_practices.Components.Model.YouonKatakana", null)
                        .WithMany()
                        .HasForeignKey("YouonKatakanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("japanese_character_practices.Components.Model.YouonHiragana", b =>
                {
                    b.HasOne("japanese_character_practices.Components.Model.GojuuonHiragana", "GojuuonHiragana")
                        .WithMany()
                        .HasForeignKey("UnicodeBase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GojuuonHiragana");
                });

            modelBuilder.Entity("japanese_character_practices.Components.Model.YouonKatakana", b =>
                {
                    b.HasOne("japanese_character_practices.Components.Model.GojuuonKatakana", "GojuuonKatakana")
                        .WithMany()
                        .HasForeignKey("UnicodeBase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GojuuonKatakana");
                });
#pragma warning restore 612, 618
        }
    }
}
