// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using japanese_character_practices.Components.Data;

#nullable disable

namespace japanese_character_practices.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("japanese_character_practices.Components.Model.JapaneseGojuuonCharacter", b =>
                {
                    b.Property<string>("Unicode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Japanese")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isDakuten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isNative")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isSutegana")
                        .HasColumnType("INTEGER");

                    b.HasKey("Unicode");

                    b.ToTable("japaneseGojuuonCharacters");
                });

            modelBuilder.Entity("japanese_character_practices.Components.Model.JapaneseYouonCharacter", b =>
                {
                    b.Property<string>("Unicode")
                        .HasColumnType("TEXT");

                    b.Property<string>("JapaneseAddon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JapaneseBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isDakuten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isNative")
                        .HasColumnType("INTEGER");

                    b.HasKey("Unicode");

                    b.ToTable("japaneseYouonCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
